#!/usr/bin/env bash

set -e

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

echo 'Install homebrew'
echo '----------------'
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup  || true
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

echo 'Install fonts'
echo '-----------------'
brew install --cask font-fira-code

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
chsh -s `which zsh`

echo 'Installing zsh plugins'
echo '------------'
git clone https://github.com/jessarcher/zsh-artisan.git ~/.oh-my-zsh/custom/plugins/artisan

echo 'Setup git configs'
echo '------------'

# Add global gitignore and setup editor
rm -f $HOME/.global-gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile "$HOME/.global-gitignore"
git config --global include.path "$HOME/.dotfiles/config/.gitconfig"
# force default config values to be used
git config --global core.autocrlf false
git config --global core.eol native
git config --global core.editor "code --wait"
# Register git hooks
git config --global core.hooksPath ~/.dotfiles/git-hooks

echo 'Create symlinks'
echo '------------'

# Symlink zsh prefs
rm -f $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm -f $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm -rf $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

echo 'Install zsh theme remy'
echo '------------'
rm $HOME/.oh-my-zsh/custom/themes/remy.zsh-theme || true
ln -s $HOME/.dotfiles/zshrc/remy.zsh-theme $HOME/.oh-my-zsh/custom/themes/remy.zsh-theme

echo 'Activate z'
echo '------------'
cd ~/.dotfiles/shell
chmod +x z.sh

echo 'install z fork'
echo '------------'
git clone https://github.com/agkozak/zsh-z  $HOME/.oh-my-zsh/custom/plugins/zsh-z

# echo 'Install node version manager (nvm)'
# echo '-----------'
# brew install nvm

# Ensure we use the Homebrew-installed nvm (some setups export NVM_DIR elsewhere, e.g. Herd)
# export NVM_DIR="$HOME/.nvm"
# mkdir -p "$NVM_DIR"
# \. "$(brew --prefix nvm)/nvm.sh"


echo 'Install pkg-config'
echo '------------------'
brew install pkg-config

echo 'Install wget'
echo '------------'
brew install wget

echo 'Install httpie'
echo '--------------'
brew install httpie

echo 'Install ncdu'
echo '------------'
brew install ncdu

echo 'Install hub'
echo '-----------'
brew install hub

echo 'Install ack'
echo '-----------'
brew install ack

echo 'Install tldr'
echo '-----------'
brew install tldr

echo 'Install dig'
echo '-----------'
brew install bind

echo 'Install nmap'
echo '-----------'
brew install nmap

echo 'Install fzf'
echo '-----------'
brew install fzf
$(brew --prefix)/opt/fzf/install

echo 'Install fswatch'
echo '-----------'
brew install fswatch

echo 'Install Visual Studio Code'
echo '-----------------'
brew install --cask  visual-studio-code

echo 'Install Cursor'
echo '--------------'
brew install --cask cursor

echo 'Install larvel herd'
echo '---------------------'
brew install --cask herd

echo 'Install setapp'
echo '---------------------'
brew install --cask setapp

echo 'Install some nice quicklook plugins'
echo '-----------------------------------'
# brew  install --cask --force qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzip webp-quicklook suspicious-package

echo 'Install pnpm'
echo '------------'
npm install -g pnpm

echo 'Install composer'
echo '-------------------'
brew install composer

echo 'Install ghostscript'
echo '-------------------'
brew install ghostscript

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions

echo 'Install prettyping'
echo '---------------------------'
brew install prettyping

echo 'Install ettercap'
echo '---------------------------'
brew install ettercap

echo 'Install ffmpeg'
echo '---------------------------'
brew install ffmpeg

echo 'Install gpg'
echo '---------------------------'
brew install gpg


echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc/iTerm Profile.json'
echo '3. Allow sudo permittance with fingerprint. Futher instructions in ~/.dotfiles/misc/fingerprint.sh'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '2. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'